package types

import (
	"slices"
	"time"
)

// UtilityProviderInfo provides metadata about a utility provider.
type UtilityProviderInfo struct {
	ID     string            `json:"id"`
	Name   string            `json:"name"`
	Rates  []UtilityRateInfo `json:"rates"`
	Hidden bool              `json:"hidden,omitempty"`
}

// UtilityRateInfo provides metadata about a specific utility rate.
type UtilityRateInfo struct {
	ID      string                                                `json:"id"`
	Name    string                                                `json:"name"`
	Options []UtilityRateOption                                   `json:"options"`
	GetFees func(UtilityRateOptions) ([]UtilityFeesPeriod, error) `json:"-"`
	GetVPP  func(UtilityRateOptions) (UtilityVPPInfo, error)      `json:"-"`
}

// UtilityOptionType defines the type of input field for a utility option.
type UtilityOptionType string

const (
	UtilityOptionTypeSelect UtilityOptionType = "select"
	UtilityOptionTypeSwitch UtilityOptionType = "switch"
)

// UtilityRateOption represents a single configuration option for a utility rate.
type UtilityRateOption struct {
	Field       string                `json:"field"`
	Name        string                `json:"name"`
	Type        UtilityOptionType     `json:"type"`
	Description string                `json:"description,omitempty"`
	Choices     []UtilityOptionChoice `json:"choices,omitempty"` // Populated if Type is UtilityOptionTypeSelect
	Default     any                   `json:"default,omitempty"`
	Hidden      bool                  `json:"hidden,omitempty"`
}

// UtilityOptionChoice represents a single choice in a select-type utility option.
type UtilityOptionChoice struct {
	Value string `json:"value"`
	Name  string `json:"name"`
}

// Price represents the cost of electricity in a time interval.
type Price struct {
	Provider string    `json:"provider"`
	TSStart  time.Time `json:"tsStart"`
	TSEnd    time.Time `json:"tsEnd"`

	// DollarsPerKWH is the base cost of electricity in the time interval.
	DollarsPerKWH float64 `json:"dollarsPerKWH"`

	// GridUseDollarsPerKWH is the additional cost of electricity for it to be
	// delivered to the home via the grid in the time interval. This is added to
	// the base price when using the grid.
	GridUseDollarsPerKWH float64 `json:"gridUseDollarsPerKWH,omitempty"`

	// GenerationCreditDollarsPerKWH is the credit given for electricity generated by
	// the home and delivered to the grid in the time interval. This is separate
	// from the base price and the grid use price.
	GenerationCreditDollarsPerKWH float64 `json:"generationCreditDollarsPerKWH,omitempty"`

	// SeparateGenerationCredit is true if the generation credit is separate from the base
	// price and the grid use price. If false, then we ignore
	// GenerationCreditDollarsPerKWH. The separate bool allows us to handle for a period
	// where the generation credit is either zero or separate from the base price.
	SeparateGenerationCredit bool `json:"separateGenerationCredit,omitempty"`

	// GenerationAdjustmentDollarsPerKWH is an adjustment applied to generated energy.
	// For Connecticut Eversource, exports are via the Renewable Energy Solutions Rider,
	// which is standard net metering but with a -$0.0402/kWh fee/adjustment applied to generated energy.
	// If SeparateGenerationCredit is false (1:1 net metering or standard net metering),
	// this adjustment is added to the base rate for export credits (i.e. DollarsPerKWH + GenerationAdjustmentDollarsPerKWH).
	// If NetMetering is active (e.g. min/max price valuation), this adjustment is applied to the max or min price (excluding 0).
	GenerationAdjustmentDollarsPerKWH float64 `json:"generationAdjustmentDollarsPerKWH,omitempty"`

	// PeriodName is the name of the utility pricing period for this interval (e.g. "Peak", "Off-Peak").
	PeriodName string `json:"periodName,omitempty"`
}

// PriceState embeds Price and adds a Confirmed flag.
type PriceState struct {
	Price
	Confirmed bool      `json:"confirmed"`
	TSUpdated time.Time `json:"tsUpdated"`
}

// Contains checks if a time is within the price interval.
func (p *Price) Contains(ts time.Time) bool {
	return !ts.Before(p.TSStart) && (p.TSEnd.IsZero() || ts.Before(p.TSEnd))
}

// UtilityRateOptions represents the options for the utility rate.
type UtilityRateOptions struct {
	RateClass            string `json:"rateClass,omitempty"`
	VariableDeliveryRate bool   `json:"variableDeliveryRate,omitempty"`
	NetMeteringCredits   bool   `json:"netMeteringCredits,omitempty"`
	NetMeteringScheme    string `json:"netMeteringScheme,omitempty"`
	PeakPeriodOption     string `json:"peakPeriodOption,omitempty"`
	GenerationRate       string `json:"generationRate,omitempty"`
	Location             string `json:"location,omitempty"`
	EVCredit             bool   `json:"evCredit,omitempty"`
	VPPProgram           string `json:"vppProgram,omitempty"`
}

type UtilityHourPeriod struct {
	// HourStart is the optional inclusive hour of the applicable period. If it is zero,
	// then it applies to all hours. This is checked after the Start and End times
	// have been checked.
	HourStart int `json:"hourStart"`

	// MinuteStart is the optional inclusive minute of the start hour.
	MinuteStart int `json:"minuteStart,omitempty"`

	// HourEnd is the optional exclusive hour of the applicable period. If it is zero,
	// then it applies to all hours. This is checked after the Start and End times
	// have been checked.
	HourEnd int `json:"hourEnd"`

	// MinuteEnd is the optional exclusive minute of the end hour.
	MinuteEnd int `json:"minuteEnd,omitempty"`
}

// TimePeriod defines a particular time-based period
type TimePeriod struct {
	// Name is a short human-friendly name to identify the period
	Name string `json:"name,omitempty"`

	// Start is the optional inclusive start time of the applicable period. If it is zero,
	// then it applies from the beginning of time.
	Start time.Time `json:"start,omitempty"`

	// End is the optional exclusive end time of the applicable period. If it is zero,
	// then it applies until the end of time.
	End time.Time `json:"end,omitempty"`

	// Hours is the optional list of hours that the period applies to. If it is empty,
	// then it applies to all hours. This is checked after the Start and End times
	// have been checked.
	Hours []UtilityHourPeriod `json:"hours,omitempty"`

	// DaysOfTheWeek is the list of days of the week this period applies. If it is
	// empty, then it applies to all days of the week. This is checked after the
	// Start and End times have been checked.
	DaysOfTheWeek []time.Weekday `json:"daysOfTheWeek,omitempty"`

	// LocationPtr is the location of the period. If it is empty then we won't change
	// the time zone of the sent time
	LocationPtr *time.Location `json:"-"`

	// HoursNot means it applies to all hours except the hours in Hours.
	HoursNot bool `json:"hoursNot,omitempty"`

	// SpecificDates is the list of specific dates (formatted as YYYY-MM-DD) that this period applies to.
	SpecificDates []string `json:"specificDates,omitempty"`

	// SpecificDatesNot means it applies to all dates except the dates in SpecificDates.
	SpecificDatesNot bool `json:"specificDatesNot,omitempty"`
}

type UtilityPeriodStartEnd struct {
	Start time.Time
	End   time.Time
}

// Contains checks if a time is within the period.
func (p *TimePeriod) Contains(t time.Time) (bool, UtilityPeriodStartEnd, error) {
	if p.LocationPtr != nil {
		t = t.In(p.LocationPtr)
	}
	if !p.Start.IsZero() && t.Before(p.Start) {
		return false, UtilityPeriodStartEnd{}, nil
	}
	// period.End is exclusive: skip if the price starts at or after End
	if !p.End.IsZero() && !t.Before(p.End) {
		return false, UtilityPeriodStartEnd{}, nil
	}

	if len(p.SpecificDates) > 0 {
		dateStr := t.Format("2006-01-02")
		containsDate := slices.Contains(p.SpecificDates, dateStr)
		if p.SpecificDatesNot {
			if containsDate {
				return false, UtilityPeriodStartEnd{}, nil
			}
		} else {
			if !containsDate {
				return false, UtilityPeriodStartEnd{}, nil
			}
		}
	}

	startEnd := UtilityPeriodStartEnd{
		Start: p.Start,
		End:   p.End,
	}
	if len(p.Hours) > 0 {
		tMin := t.Hour()*60 + t.Minute()
		inRange := false
		for _, hour := range p.Hours {
			startMin := hour.HourStart*60 + hour.MinuteStart
			endMin := hour.HourEnd*60 + hour.MinuteEnd
			if tMin >= startMin && tMin < endMin {
				hStart := time.Date(t.Year(), t.Month(), t.Day(), hour.HourStart, hour.MinuteStart, 0, 0, t.Location())
				hEnd := time.Date(t.Year(), t.Month(), t.Day(), hour.HourEnd, hour.MinuteEnd, 0, 0, t.Location())
				if startEnd.Start.IsZero() || hStart.After(startEnd.Start) {
					startEnd.Start = hStart
				}
				if startEnd.End.IsZero() || hEnd.Before(startEnd.End) {
					startEnd.End = hEnd
				}
				inRange = true
				break
			}
		}
		if p.HoursNot {
			inRange = !inRange
		}
		if !inRange {
			return false, UtilityPeriodStartEnd{}, nil
		}
	}

	if len(p.DaysOfTheWeek) > 0 && !slices.Contains(p.DaysOfTheWeek, t.Weekday()) {
		return false, UtilityPeriodStartEnd{}, nil
	}
	return true, startEnd, nil
}

// UtilityFeesPeriod represents a period of time with a fee.
type UtilityFeesPeriod struct {
	TimePeriod

	// DollarsPerKWH is the fee per kWh in the time interval.
	DollarsPerKWH float64 `json:"dollarsPerKWH,omitempty"`

	// GridAdditional is true if the fee is additional to the grid use price but is
	// not credited when energy is exported to the grid.
	GridAdditional bool `json:"gridAdditional,omitempty"`

	// SeparateGenerationCredit is true if the generation credit is separate from
	// the base price for this period. Some utilities ALWAYS have a separate
	// generation credit and therefore this could be false for those utilities but
	// other utilities might have a generation credit that is separate from the base
	// price for some periods and not for others in which case this would be used.
	SeparateGenerationCredit bool `json:"separateGenerationCredit,omitempty"`

	// DollarsPerKWHPreMultiple is multiplied against the base price before other fees
	// and then added to the total. In general, this should be less than 1.
	DollarsPerKWHPreMultiple float64 `json:"dollarsPerKWHPreMultiple,omitempty"`

	// GenerationAdjustmentDollarsPerKWH is the adjustment to generation credits.
	GenerationAdjustmentDollarsPerKWH float64 `json:"generationAdjustmentDollarsPerKWH,omitempty"`

	// Description is a description of the fee.
	Description string `json:"description"`
}

// Apply checks if the period contains the price start time and if so applies the fee logic.
// p is the accumulated Price, while originalPrice is the original price before any fees
// were applied and is used to calculate fees that are a multiple of the base price.
func (up *UtilityFeesPeriod) Apply(p Price, originalPrice Price) (Price, error) {
	contains, _, err := up.Contains(p.TSStart)
	if err != nil {
		return Price{}, err
	}
	if !contains {
		return p, nil
	}

	if up.GenerationAdjustmentDollarsPerKWH != 0 {
		p.GenerationAdjustmentDollarsPerKWH += up.GenerationAdjustmentDollarsPerKWH
	}

	switch {
	case up.SeparateGenerationCredit:
		p.GenerationCreditDollarsPerKWH += up.DollarsPerKWH
		p.SeparateGenerationCredit = true
	case up.GridAdditional:
		if up.DollarsPerKWHPreMultiple != 0 {
			p.GridUseDollarsPerKWH += originalPrice.DollarsPerKWH * up.DollarsPerKWHPreMultiple
		} else {
			p.GridUseDollarsPerKWH += up.DollarsPerKWH
		}
	case up.DollarsPerKWHPreMultiple != 0:
		p.DollarsPerKWH += originalPrice.DollarsPerKWH * up.DollarsPerKWHPreMultiple
	default:
		p.DollarsPerKWH += up.DollarsPerKWH
	}

	// ignore names for export periods and fees periods
	if !up.SeparateGenerationCredit && !up.GridAdditional && up.Name != "" {
		p.PeriodName = up.Name
	}

	return p, nil
}

// ApplyUtilityFeesPeriods takes a price and a slice of periods and applies the fees
// for every period that contains the price's start time, returning the result.
func ApplyUtilityFeesPeriods(p Price, periods []UtilityFeesPeriod) (Price, error) {
	newPrice := p
	for _, period := range periods {
		var err error
		newPrice, err = period.Apply(newPrice, p)
		if err != nil {
			return Price{}, err
		}
	}
	return newPrice, nil
}

// UtilityVPPPeriod represents a period of time with utility-mandated VPP events.
type UtilityVPPPeriod struct {
	TimePeriod
	ReserveSOC float64 `json:"reserveSOC"`
}

// UtilityVPPInfo holds VPP events information.
type UtilityVPPInfo struct {
	Mandatory []UtilityVPPPeriod `json:"mandatory"`
}
